### ISSUE TITLE
Cant execute

### ISSUE THREAD

**Issue by lprawetz** [Stromner/TQCharacterEditor#21]
Hey man,
nice project!
I'm new to github so i'm not sure if this is the right way to contact you.
I cant get TQCE executed, could you point me in the right direction?

**Comment by grasmanek94** [comment]
I'm also wondering how I would run this?

**Comment by periodic** [comment]
I just ran the app with roughly the following.

```
cd Application
mvn package
mvn exec:java -D exec.mainClass="tq.character.editor.TqCharacterEditor"
```

I was able to browse to the save file and open it, though the skills tab was blank, which is what I was hoping to reset.

**Comment by Stromner** [comment]
Hey! Incredibly sorry that I missed this issue, had notifications for github turned off and haven't worked on it in a while. I haven't released anything that can be executed stand-alone as I've been running it from inside my IDE during development. @periodic mentioned how you can execute it as a workaround but it does require Maven setup locally. I will try to release and update the documentation later today.

@periodic Yeah, sorry my build doesn't have support for that yet. I have it planned whenever I get more free time again. Check out https://github.com/epinter/tqrespec for a full character editor.

**Comment by Stromner** [comment]
@lprawetz better late than never I guess, but I've created an executable jar so you can at least start the application. Start it with "java -jar Application-1.0-SNAPSHOT-exec"

I will close the issue, please re-open if you still can't start it.
